---
galaxy_info:
  author: Kálmán Szalai - KAMI
  description: "Ansible role for configuring Oracle Java 8"
  license: MIT
  min_ansible_version: 2.0

  categories:
    - development
    - system
    - java

  platforms:
    - name: EL
      versions:
        - all

dependencies: []:
