---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: java-centos6-11-jdk
    image: geerlingguy/docker-centos6-ansible
    image_version: latest
    groups:
      - jdk

  - name: java-centos7-11-jdk
    image: geerlingguy/docker-centos7-ansible
    image_version: latest
    privileged: true
    groups:
      - jdk

  - name: java-centos8-11-jdk
    image: geerlingguy/docker-centos8-ansible
    image_version: latest
    privileged: true
    groups:
      - jdk
      - python3

  - name: java-centos6-11-server_jre
    image: geerlingguy/docker-centos6-ansible
    image_version: latest
    groups:
      - jdk

  - name: java-centos7-11-server_jre
    image: geerlingguy/docker-centos7-ansible
    image_version: latest
    privileged: true
    groups:
      - server_jre

  - name: java-centos8-11-server_jre
    image: geerlingguy/docker-centos8-ansible
    image_version: latest
    privileged: true
    groups:
      - server_jre
      - python3

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      jdk:
        java_type: 'jdk'
      server_jre:
        java_type: 'server-jre'
      python3:
        ansible_python_interpreter: '/usr/bin/env python3'
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
