---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: java-centos6-8-jdk
    image: centos
    image_version: 6.8
    groups:
      - jdk

  - name: java-centos6-8-server-jre
    image: centos
    image_version: 6.8
    groups:
      - jdk

  - name: java-centos7-jdk
    image: milcom/centos7-systemd
    image_version: latest
    privileged: true
    groups:
      - server_jre

  - name: java-centos7-server-jre
    image: milcom/centos7-systemd
    image_version: latest
    privileged: true
    groups:
      - server_jre

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      jdk:
        java_type: 'jdk'
      server_jre:
        java_type: 'server-jre'
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
