---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-centos6-8-jdk
    image: centos
    image_version: 6.8
    groups:
      - group1

  - name: java-centos6-8-server-jre
    image: centos
    image_version: 6.8
    groups:
      - group1


  - name: java-centos7-jdk
    image: milcom/centos7-systemd
    image_version: latest
    privileged: True
    groups:
      - group1

  - name: java-centos7-server-jre
    image: milcom/centos7-systemd
    image_version: latest
    privileged: True
    groups:
      - group1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
